baseurl = "https://www.indeviduals.com"
languageCode = "en-us"
theme = "hello-friend-ng"

[author]
  name = "Marcus Karlsson"
  homepage = "https://www.indeviduals.com"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Just a short insight to my life as a dev, and working as a cloud consultant primarily focusing on AWS"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "indeviduals"
    subtitle = "Just a short insight"
    keywords = "indev, dev, programming, aws, cloud, automation"
    copyright = "indeviduals"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "indeviduals"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase/"
      [[languages.en.menu.main]]
        identifier = "blog"
        name       = "Blog"
        url        = "/posts/"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts/"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase/"